name: Deploy Buzzer to sarcastichedgehog.com

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout buzzer game repository
        uses: actions/checkout@v4
        with:
          path: buzzer_game

      - name: Create config.js for buzzer (if not already present)
        working-directory: ./buzzer_game
        run: |
          if [ ! -f "config.js" ]; then
            echo "Generating config.js from secrets..."
            echo "window.APP_CONFIG = {" > config.js
            echo "  API_KEY: \"${{ secrets.MULTISYNQ_API_KEY }}\"," >> config.js
            echo "  APP_ID: \"${{ secrets.MULTISYNQ_APP_ID }}\"" >> config.js
            echo "  BASE_URL: \"${{ secrets.MULTISYNQ_BASE_URL }}\"" >> config.js

            echo "};" >> config.js
          else
            echo "config.js already exists, skipping overwrite."
          fi

      - name: Checkout sarcastichedgehog.com website repository
        uses: actions/checkout@v4
        with:
          repository: SarcyHedgehog/sarcastichedgehog.com
          path: website_repo
          token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}

      - name: Copy game files to website repository
        run: |
          TARGET_DIR="./website_repo/buzzer"
          mkdir -p "$TARGET_DIR"

          echo "Copying core files..."
          cp ./buzzer_game/index.html "$TARGET_DIR/"
          cp ./buzzer_game/manifest.json "$TARGET_DIR/"
          cp ./buzzer_game/sw.js "$TARGET_DIR/"
          cp ./buzzer_game/config.js "$TARGET_DIR/"

          echo "Checking for images or additional assets..."
          if [ -d "./buzzer_game/images" ]; then
            cp -r ./buzzer_game/images "$TARGET_DIR/"
          fi

        shell: bash

      - name: Commit and push changes to website repository
        env:
          GIT_USER_NAME: "GitHub Actions Bot"
          GIT_USER_EMAIL: "actions@github.com"
        run: |
          cd ./website_repo
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to commit."
          else
            git config user.name "${GIT_USER_NAME}"
            git config user.email "${GIT_USER_EMAIL}"
            git add .
            git commit -m "Deploy Buzzer game update from buzzer2 repository"
            git push origin main
          fi
